services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 10

  redis:
    image: redis:7
    command: ["redis-server","--appendonly","yes"]
    volumes:
      - redis_data:/data

  backend:
    build: ./backend
    env_file: .env
    environment:
      POETRY_VIRTUALENVS_CREATE: "false"
      DATABASE_URL: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
      REDIS_URL: ${REDIS_URL}
      SUMMARIZER_MODEL: ${SUMMARIZER_MODEL}
    volumes:
      - ./backend/src:/app/src:rw
    command: >
      bash -lc "poetry run uvicorn src.app.main:app
      --host 0.0.0.0 --port ${API_PORT} --reload"
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started

  worker:
    build: ./worker
    env_file: .env
    environment:
      POETRY_VIRTUALENVS_CREATE: "false"
      DATABASE_URL: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
      REDIS_URL: ${REDIS_URL}
    volumes:
      - ./worker/src:/app/src:rw
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started

  frontend:
    build: ./frontend
    environment:
      - VITE_API_BASE=${VITE_API_BASE}
    volumes:
      - ./frontend:/app:rw
      - /app/node_modules
    expose: ["5173"]
    profiles: ["dev"]

  proxy:
    image: nginx:1.27
    volumes:
      - ./proxy/nginx.dev.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "80:80"
    depends_on: [backend, frontend]
    profiles: ["dev"]

volumes:
  postgres_data:
  redis_data:
networks:
  default:
    name: podolsk-net
    driver: bridge
    ipam:
      config:
        - subnet: 172.15.0.0/16
